fix: 'str' object has no attribute 'decode' (#49).
Raised in only python3. However, removing the decoding in line https://github.com/mzechmeister/serval/blob/57c4bf51e368c011212a1f52193f8aacf131327a/src/read_spec.py#L707 would lead to:

UnicodeDecodeError: \'utf-8\' codec can\'t decode byte 0xe0 in position 6470: invalid continuation byte

Probably caused by a '%'!?.
It seems better to open the fits file in binary mode.