fix: Failure of ofacauto.
The option ofacauto resulted in:
File "serval", line 1904, in serval
    yfit[ind2] = smod(ww[o][ind2])
TypeError: int object is not subscriptable

This is related to the removal of template.fits (#61).
The variables ww and yfit were removed in 57b8358.